* Eazy-Documentation [[https://travis-ci.org/numcl/numcl][https://travis-ci.org/eazy-documentation/eazy-documentation.svg]]

+ *One-shot solution to the CL library documentation generator.*
  + It *does not require any custom macro/read-macro for annotating your API.*
    Existing documentation generator supports only a limited number of macros (e.g. =defun=),
    or need user-defined extensions to the parser that extracts the
    documentation strings.  In contrast, this library runs based on the heuristic
    decision and ranking.
  + It *searches the repository for any potential documentation files and embed*
    *them in the output as html*. Some library (especially the old ones like CFFI)
    contains a separate documentation / manual as texinfo documents, but they
    will be all embedded in the output.
  + It supports any markup format supported by Pandoc and makeinfo.

+ *Compress, compress, compress!*
  + *Best documentation gives you the most with the least text.*
    Bloated, redundant entries are harmful.
    Eazy-Documentation therefore provides a compact documentation by compressing the documentation entries
    in a run-length encoding manner -- similar, partly identical entries are merged together
    as much as possible.

+ *Respect the code structure and ordering.*
  + Well-written library has a nice, intuitive code structure.
    This must be exploited by the documentation generator -- inspired by [Quickdocs](http://quickdocs.org/).

** Author, License, Copyright

Masataro Asai (guicho2.71828@gmail.com)

Licensed under LGPL v3.

Copyright (c) 2019 IBM Corporation


